name: Openfabric Testnet Test workflow

on: workflow_dispatch


jobs:
  run-tests:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Appium
        run: | 
          npm install -g appium
          appium driver install uiautomator2
          appium &>/dev/null &

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn clean test